// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package media

import (
	"syscall"
	"unsafe"

	"github.com/dece2183/media-winrt-go/windows/foundation"
	"github.com/go-ole/go-ole"
)

const SignaturePlaybackPositionChangeRequestedEventArgs string = "rc(Windows.Media.PlaybackPositionChangeRequestedEventArgs;{b4493f88-eb28-4961-9c14-335e44f3e125})"

type PlaybackPositionChangeRequestedEventArgs struct {
	ole.IUnknown
}

func (impl *PlaybackPositionChangeRequestedEventArgs) GetRequestedPlaybackPosition() (foundation.TimeSpan, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiPlaybackPositionChangeRequestedEventArgs))
	defer itf.Release()
	v := (*iPlaybackPositionChangeRequestedEventArgs)(unsafe.Pointer(itf))
	return v.GetRequestedPlaybackPosition()
}

const GUIDiPlaybackPositionChangeRequestedEventArgs string = "b4493f88-eb28-4961-9c14-335e44f3e125"
const SignatureiPlaybackPositionChangeRequestedEventArgs string = "{b4493f88-eb28-4961-9c14-335e44f3e125}"

type iPlaybackPositionChangeRequestedEventArgs struct {
	ole.IInspectable
}

type iPlaybackPositionChangeRequestedEventArgsVtbl struct {
	ole.IInspectableVtbl

	GetRequestedPlaybackPosition uintptr
}

func (v *iPlaybackPositionChangeRequestedEventArgs) VTable() *iPlaybackPositionChangeRequestedEventArgsVtbl {
	return (*iPlaybackPositionChangeRequestedEventArgsVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iPlaybackPositionChangeRequestedEventArgs) GetRequestedPlaybackPosition() (foundation.TimeSpan, error) {
	var out foundation.TimeSpan
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetRequestedPlaybackPosition,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.TimeSpan
	)

	if hr != 0 {
		return foundation.TimeSpan{}, ole.NewError(hr)
	}

	return out, nil
}
