// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package media

import (
	"syscall"
	"unsafe"

	"github.com/dece2183/media-winrt-go/windows/foundation"
	"github.com/dece2183/media-winrt-go/windows/storage"
	"github.com/go-ole/go-ole"
)

const SignatureSystemMediaTransportControlsDisplayUpdater string = "rc(Windows.Media.SystemMediaTransportControlsDisplayUpdater;{8abbc53e-fa55-4ecf-ad8e-c984e5dd1550})"

type SystemMediaTransportControlsDisplayUpdater struct {
	ole.IUnknown
}

func (impl *SystemMediaTransportControlsDisplayUpdater) CopyFromFileAsync(mType MediaPlaybackType, source *storage.StorageFile) (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSystemMediaTransportControlsDisplayUpdater))
	defer itf.Release()
	v := (*iSystemMediaTransportControlsDisplayUpdater)(unsafe.Pointer(itf))
	return v.CopyFromFileAsync(mType, source)
}

func (impl *SystemMediaTransportControlsDisplayUpdater) Update() error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSystemMediaTransportControlsDisplayUpdater))
	defer itf.Release()
	v := (*iSystemMediaTransportControlsDisplayUpdater)(unsafe.Pointer(itf))
	return v.Update()
}

const GUIDiSystemMediaTransportControlsDisplayUpdater string = "8abbc53e-fa55-4ecf-ad8e-c984e5dd1550"
const SignatureiSystemMediaTransportControlsDisplayUpdater string = "{8abbc53e-fa55-4ecf-ad8e-c984e5dd1550}"

type iSystemMediaTransportControlsDisplayUpdater struct {
	ole.IInspectable
}

type iSystemMediaTransportControlsDisplayUpdaterVtbl struct {
	ole.IInspectableVtbl

	GetType            uintptr
	SetType            uintptr
	GetAppMediaId      uintptr
	SetAppMediaId      uintptr
	GetThumbnail       uintptr
	SetThumbnail       uintptr
	GetMusicProperties uintptr
	GetVideoProperties uintptr
	GetImageProperties uintptr
	CopyFromFileAsync  uintptr
	ClearAll           uintptr
	Update             uintptr
}

func (v *iSystemMediaTransportControlsDisplayUpdater) VTable() *iSystemMediaTransportControlsDisplayUpdaterVtbl {
	return (*iSystemMediaTransportControlsDisplayUpdaterVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iSystemMediaTransportControlsDisplayUpdater) CopyFromFileAsync(mType MediaPlaybackType, source *storage.StorageFile) (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().CopyFromFileAsync,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(mType),                  // in MediaPlaybackType
		uintptr(unsafe.Pointer(source)), // in storage.StorageFile
		uintptr(unsafe.Pointer(&out)),   // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iSystemMediaTransportControlsDisplayUpdater) Update() error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().Update,
		uintptr(unsafe.Pointer(v)), // this
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
