// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package playback

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureMediaPlaybackCommandManager string = "rc(Windows.Media.Playback.MediaPlaybackCommandManager;{5acee5a6-5cb6-4a5a-8521-cc86b1c1ed37})"

type MediaPlaybackCommandManager struct {
	ole.IUnknown
}

func (impl *MediaPlaybackCommandManager) SetIsEnabled(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiMediaPlaybackCommandManager))
	defer itf.Release()
	v := (*iMediaPlaybackCommandManager)(unsafe.Pointer(itf))
	return v.SetIsEnabled(value)
}

const GUIDiMediaPlaybackCommandManager string = "5acee5a6-5cb6-4a5a-8521-cc86b1c1ed37"
const SignatureiMediaPlaybackCommandManager string = "{5acee5a6-5cb6-4a5a-8521-cc86b1c1ed37}"

type iMediaPlaybackCommandManager struct {
	ole.IInspectable
}

type iMediaPlaybackCommandManagerVtbl struct {
	ole.IInspectableVtbl

	GetIsEnabled                 uintptr
	SetIsEnabled                 uintptr
	GetMediaPlayer               uintptr
	GetPlayBehavior              uintptr
	GetPauseBehavior             uintptr
	GetNextBehavior              uintptr
	GetPreviousBehavior          uintptr
	GetFastForwardBehavior       uintptr
	GetRewindBehavior            uintptr
	GetShuffleBehavior           uintptr
	GetAutoRepeatModeBehavior    uintptr
	GetPositionBehavior          uintptr
	GetRateBehavior              uintptr
	AddPlayReceived              uintptr
	RemovePlayReceived           uintptr
	AddPauseReceived             uintptr
	RemovePauseReceived          uintptr
	AddNextReceived              uintptr
	RemoveNextReceived           uintptr
	AddPreviousReceived          uintptr
	RemovePreviousReceived       uintptr
	AddFastForwardReceived       uintptr
	RemoveFastForwardReceived    uintptr
	AddRewindReceived            uintptr
	RemoveRewindReceived         uintptr
	AddShuffleReceived           uintptr
	RemoveShuffleReceived        uintptr
	AddAutoRepeatModeReceived    uintptr
	RemoveAutoRepeatModeReceived uintptr
	AddPositionReceived          uintptr
	RemovePositionReceived       uintptr
	AddRateReceived              uintptr
	RemoveRateReceived           uintptr
}

func (v *iMediaPlaybackCommandManager) VTable() *iMediaPlaybackCommandManagerVtbl {
	return (*iMediaPlaybackCommandManagerVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iMediaPlaybackCommandManager) SetIsEnabled(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetIsEnabled,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
